spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/kdkdb?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: root
    password: root
  jpa: 
    database: mysql
    generate-ddl: true
    show-sql: true
  thymeleaf:
    cache: false
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    view-names: thymeleaf/*

server:
  port: 8082
