spring:
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/kdkdb?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: root
    password: root
  liquibase:
    change-log: classpath:/schema/changelog-master.xml
  jpa: 
    database: mysql
    generate-ddl: true
    show-sql: true
  thymeleaf:
    cache: false
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    view-names: thymeleaf/*
  security:  
    oauth2:  
      client:  
        clientId: 856610290889-kub4iuarh5fqn2h27ubui22n13mcfcid.apps.googleusercontent.com
        clientSecret: QgWg3vah1Y4jMdJfSC0oG8c8
  profiles:
    include: oauth

server:
  port: 8082
